detectors:
  IrresponsibleModule:
    enabled: false
  UncommunicativeVariableName:
    enabled: false
  NestedIterators:
    ignore_iterators:
      - each_object
  UtilityFunction:
    enabled: false
  UncommunicativeMethodName:
    enabled: false
exclude_paths:
  - bin
  - client
